### Feature Selection - Variance Threshold
**Description**: Remove features with low variance.

In [ ]:
# write your code from here

In [1]:
from sklearn.feature_selection import VarianceThreshold
import numpy as np

# Example data
X = np.array([[0, 2, 0, 3],
              [0, 1, 4, 3],
              [0, 1, 1, 3]])

# Initialize VarianceThreshold with a threshold (e.g., 0.2)
selector = VarianceThreshold(threshold=0.2)

# Fit and transform the data
X_selected = selector.fit_transform(X)

print("Original Data:")
print(X)
print("\nSelected Features:")
print(X_selected)

Original Data:
[[0 2 0 3]
 [0 1 4 3]
 [0 1 1 3]]

Selected Features:
[[2 0]
 [1 4]
 [1 1]]
